### ISSUE TITLE
Accessibility Tab Highlight

### ISSUE THREAD

**Issue by JakeWags** [geotrev/undernet#110]
Linux Ubuntu 18.04
Google Chrome 71.0.3578.98 official build

On the accessibility documentation page, when pressing "tab" or "shift+tab" to highlight items on the page, the outlines in the navigation area (on the left) are not aligned to the proper item.

This is the expected behavior, which is properly working for the "introduction" navigation tag:
![expectedbehavior](https://user-images.githubusercontent.com/35744963/51714894-87585700-1feb-11e9-82c7-cf8121feaae9.png)

This is the behavior for the "download", "branding", and "javascript" navigation tags:
![downloadhighlighted](https://user-images.githubusercontent.com/35744963/51714929-a0610800-1feb-11e9-9e25-84e1e9b16316.png)

This is the behavior for the "accessibility" navigation tag:
![accessibilityhighlighted](https://user-images.githubusercontent.com/35744963/51714940-ac4cca00-1feb-11e9-83e6-b288acc3a8df.png)

**Comment by geotrev** [comment]
Thanks for submitting this issue Jake! I've noticed this before but just haven't had the time to get around to fixing it.  😬 I can take a look into it soon!

As for expected behavior: the focus outline should completely wrap around the item in question (see focus outlines on other links or focusable elements on the page). I think this issue is coming from the `overflow: hidden` property currently on all accordion content containers, which is cutting off the rest of the outline.

**Comment by JakeWags** [comment]
Hi, I’m on mobile but I’ll take a look at the functionality tonight

**Comment by JakeWags** [comment]
Looks great to me, feel free to merge that in. Pretty simple fix but it made a good difference in terms of accessibility.
